- name: Install System Packages (build essentials and various utils)
  become: true
  apt:
    name:
      [
        "build-essential",
        "cmake",
        "ca-certificates",
        "ccache",
        "pkg-config",
        "clang",
        "clangd",
        "lldb",
        "apt-transport-https",
        "unzip",
        "python3-pip",
        "pipx",
        "libtool",
        "ninja-build",
        "gettext",
        "curl",
        "wget",
      ]
  tags:
    - core

- name: Install rustup
  shell: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
  tags:
    - core
    - rust
